name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Limit how many instances of this workflow a pull request
# can run at once.
# Upon commit, if a instance is in progress for the same
# pull request, cancel it. The latest workflow is
# the priority.
concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
    push:

    # Manually trigger the workflow from the "Actions"
    # tab in the GitHub repo.
    workflow_dispatch:

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    name: Send Slack Message
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: "Set up template variables"
        id: template_vars
        run: |
          JSON_FROM_FILE=$(cat ./.github/workflows/slack-message-vars.json | jq .)
          JSON_EXPANDED="$JSON_FROM_FILE"
          RESULT=$(echo "$JSON_EXPANDED" | jq -c '. | tostring')
          echo "Processed JSON: $RESULT"
          echo "FINAL=$RESULT" >> $GITHUB_OUTPUT

      - name: "Set up the Slack Template"
        id: slack_template
        run: |
          TEMPLATE_VARS="${{ steps.template_vars.outputs.FINAL }}"
          FILTERED_TEMPLATE=$(echo "$TEMPLATE_VARS" | jq -f './.github/workflows/slack-message-template.jq')
          echo "$FILTERED_TEMPLATE"
          echo "$FILTERED_TEMPLATE" >> ./slack-message.json

      - name: "Dump steps context"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: "Post to Slack"
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "CJGLJLN1F"
          payload-file-path: './slack-message.json'
