name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Limit how many instances of this workflow a pull request
# can run at once.
# Upon commit, if a instance is in progress for the same
# pull request, cancel it. The latest workflow is
# the priority.
concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
    push:

    # Manually trigger the workflow from the "Actions"
    # tab in the GitHub repo.
    workflow_dispatch:

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
    steps:
    - id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "DJGLJLLFK"
        payload: |
           {
            "text": "Deployment started (In Progress)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
    - id: update-message
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      with:
        channel-id: "DJGLJLLFK"
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "text": "Deployment finished (Completed)",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Completed"
                  }
                ]
              }
            ]
          }
