name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Limit how many instances of this workflow a pull request
# can run at once.
# Upon commit, if a instance is in progress for the same
# pull request, cancel it. The latest workflow is
# the priority.
concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
    push:

    # Manually trigger the workflow from the "Actions"
    # tab in the GitHub repo.
    workflow_dispatch:

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    name: Send Slack Message
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: "Get template json"
        id: getjson
        run: |
          echo "SLACK_TEMPLATE=$(echo '{"username": "${{ github.actor }}" }' | jq -c -r -f './.github/workflows/slack-message-template.jq' | jq)" >> $GITHUB_OUTPUT

      - name: "Populate Template"
        id: populateTemplate
        run: |
          echo "${{ steps.getjson.outputs.SLACK_TEMPLATE }}"
          

#      - name: "Post to Slack"
#        uses: slackapi/slack-github-action@v1.24.0
#        env:
#          WORKFLOW_DEPLOYED_BY: ${{ github.actor }}
#        with:
#          channel-id: "CJGLJLN1F"
#          payload: ${{ steps.populateTemplate.outputs.POPULATED_TEMPLATE }}
