name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Limit how many instances of this workflow a pull request
# can run at once.
# Upon commit, if a instance is in progress for the same
# pull request, cancel it. The latest workflow is
# the priority.
concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
    push:

    # Manually trigger the workflow from the "Actions"
    # tab in the GitHub repo.
    workflow_dispatch:

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    name: Send Slack Message
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      WORKFLOW_DEPLOYED_BY: ${{ github.actor }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: "Get template json"
        id: getjson
        run: |
          echo "SLACK_TEMPLATE=$(jq -c . < ./.github/workflows/slack-message-template.json)" >> $GITHUB_OUTPUT

      - name: "Output JSON"
        run: |
          echo $(steps.getjson.outputs.SLACK_TEMPLATE)

      - name: "Post to Slack"
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "CJGLJLN1F"
          payload: ${{ steps.getjson.outputs.SLACK_TEMPLATE }}
