name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Limit how many instances of this workflow a pull request
# can run at once.
# Upon commit, if a instance is in progress for the same
# pull request, cancel it. The latest workflow is
# the priority.
concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
    push:

    # Manually trigger the workflow from the "Actions"
    # tab in the GitHub repo.
    workflow_dispatch:

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    name: Send Slack Message
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: "Get template json"
        id: getjson
        run: >
          SLACK_TEMPLATE_VARS='{"username": "${{github.actor}}"}'
          SLACK_MESSAGE_TEMPLATE="./.github/workflows/slack-message-template.jq"
          SLACK_TEMPLATE=$(echo $SLACK_TEMPLATE_VARS | jq -f $SLACK_MESSAGE_TEMPLATE | jq '.[] | tostring') 
          echo $SLACK_TEMPLATE >> $GITHUB_OUTPUT

      - name: "Post to Slack"
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "CJGLJLN1F"
          payload: ${{ steps.getjson.outputs.SLACK_TEMPLATE }}
