name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# Limit how many instances of this workflow a pull request
# can run at once.
# Upon commit, if a instance is in progress for the same
# pull request, cancel it. The latest workflow is
# the priority.
concurrency:
  group: pull-request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
    push:

    # Manually trigger the workflow from the "Actions"
    # tab in the GitHub repo.
    workflow_dispatch:

jobs:
  send_slack_message:
    runs-on: ubuntu-latest
    name: Send Slack Message
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: "Set up template variables"
        id: template_vars
        run: |
          echo "SLACK_TEMPLATE_VARS=$(jq -n --arg user \"${{ github.actor }}\" '{author: $user}')" >> $GITHUB_OUTPUT

#      - name: "Set up the Slack Template"
#        id: slack_template
#        run: >-
#          echo "SLACK_TEMPLATE=$(
#            echo ${{ toJSON(steps.template_vars.outputs.SLACK_TEMPLATE_VARS) }} |
#            jq -f './.github/workflows/slack-message-template.jq' |
#            jq '.[] | tostring'
#          )" >> $GITHUB_OUTPUT

      - name: "Dump steps context"
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

#      - name: "Post to Slack"
#        uses: slackapi/slack-github-action@v1.24.0
#        with:
#          channel-id: "CJGLJLN1F"
#          payload: ${{ steps.getjson.outputs.THETEMPLATE }}
